#!/usr/bin/env groovy

import hudson.model.*

def PROJECT_VERSION;
def VERSION;
def MVN_VERSION_CMD;
def MVN_DEPLOY_CMD;
def LIBHADOOP_SO_COPY_CMD;
pipeline {
    agent none
    stages {
        stage('Checkout') {
            agent {
                label 'ci-hadoop-v3'
            }
            steps {
               script {
                   checkout scm
                   withMaven(
                       maven: 'Maven 3.3',
                       mavenLocalRepo: '.repository',
                   ) {
                       PROJECT_VERSION = readMavenPom().getVersion()
                       VERSION="${PROJECT_VERSION}-dremio-${BUILD_TIMESTAMP}-${GIT_COMMIT[0..7]}"
                       MVN_SET_VERSION_CMD = "mvn -B versions:set versions:set-property -Dproperty=hadoop.version -DnewVersion=${VERSION}"
                       MVN_DEPLOY_CMD = "mvn clean deploy -Pnative -Drequire.snappy -Drequire.openssl -Drequire.fuse -Pdist -Dtar -DskipTests -DskipTests -DaltDeploymentRepository=dremio.nexus::default::https://repository.drem.io/content/repositories/releases/"
                       LIBHADOOP_SO_COPY_CMD = "cp hadoop-dist/target/hadoop-${VERSION}/lib/native/libhadoop.so.* libhadoop.so"
                   }
              }
            }
        }
        stage('Build libhadoop.so') {
            parallel {
                stage('x86') {
                    agent {
                        label 'ci-hadoop-v3'
                    }
                    steps {
                       script {
                           checkout scm
                           withMaven(
                                maven: 'Maven 3.3',
                                mavenLocalRepo: '.repository',
                           ) {
                                sh "${MVN_SET_VERSION_CMD}"
                                sh "${MVN_DEPLOY_CMD}"
                                sh "${LIBHADOOP_SO_COPY_CMD}"
                                sh "jar cvf hadoop-common-native-${PROJECT_VERSION}-linux.jar libhadoop.so"
                                sh "mvn -B -N deploy:deploy-file -Durl=https://repository.drem.io/content/repositories/releases/ -DrepositoryId=dremio.nexus -Dfile='hadoop-common-native-${PROJECT_VERSION}-linux.jar' -DgroupId=org.apache.hadoop -DartifactId=hadoop-common-native -Dversion=${VERSION} -Dclassifier=linux -Dpackaging=jar"
                           }
                      }
                    }
                }
                stage('ARM') {
                    agent {
                        label 'ci-hadoop-v1_central1'
                    }
                    steps {
                        script {
                             checkout scm
                             withMaven(
                                 maven: 'Maven 3.3',
                                 mavenLocalRepo: '.repository'
                             ) {
                                sh "${MVN_SET_VERSION_CMD}"
                                sh "${MVN_DEPLOY_CMD}"
                                sh "${LIBHADOOP_SO_COPY_CMD}"
                                sh "jar cvf hadoop-common-native-${PROJECT_VERSION}-linux-aarch64.jar libhadoop.so"
                                sh "mvn -B -N deploy:deploy-file -Durl=https://repository.drem.io/content/repositories/releases/ -DrepositoryId=dremio.nexus -Dfile='hadoop-common-native-${PROJECT_VERSION}-linux-aarch64.jar' -DgroupId=org.apache.hadoop -DartifactId=hadoop-common-native -Dversion=${VERSION} -Dclassifier=linux-aarch64 -Dpackaging=jar"
                             }
                       	}
                    }
                }
            }
        }
    }
}
